### ISSUE TITLE
Error message- DataSprint2

### ISSUE THREAD

**Issue by anapir** [cumc-dbmi/pmi_sprint_reporter#17]
Hi,

I've submitted some of the DataSprint2 files. When I was looking at the Data_Sprint_Reporter’s report tab, I found out when I hover over ECCHC’s submitted files, there is an error message.
Here is the error message: 
![error-message- datasprint report1](https://cloud.githubusercontent.com/assets/25771108/22931897/63c44d20-f294-11e6-8d84-6ff92dcf5cba.jpg)
Could you tell me how I can fix this issue.

Thank you,
Ana

**Comment by mark-velez** [comment]
The report indicates that the files `ecchc_visit_occurrence_datasprint_2.csv` and `ecchc_person_datasprint_2.csv` were received, but the tool was unable to load them because one or more records in those files had a non-numeric value where a numeric value was expected. For example, in `ecchc_visit_occurrence_datasprint_2.csv` the following columns are expected to contain integers: `visit_occurrence_id`, `person_id`, `visit_concept_id`, `visit_type_concept_id`, `provider_id`,`care_site_id`,`visit_source_concept_id`. Please carefully inspect the files and let us know.

**Comment by mark-velez** [comment]
As I advised in #19, you can get more detailed information if you run the tool locally and look at `pmi_sprint_reporter_log`. It should indicate that `ecchc_visit_occurrence_datasprint_2.csv` has at least one field that may be using single-quotes instead of double-quotes (e.g. in one record `visit_occurrence_id='100000'`). The [specification](https://cumc-dbmi.github.io/pmi_sprint_reporter/index.html#data-and-format) indicates that each field should be enclosed in double-quotes.

**Comment by anapir** [comment]
Thank you, Mark. I will look at the files again and make sure that there are no single-quotes.
