### ISSUE TITLE
Parse issue

### ISSUE THREAD

**Issue by johntmilnes** [cumc-dbmi/pmi_sprint_reporter#23]
Hi-  I now get parse errors in my log table:

pitt_condition_occurrence_datasprint_2.csv	'condition_start_date' is not in list
pitt_drug_exposure_datasprint_2.csv		'drug_exposure_start_date' is not in list
pitt_measurement_datasprint_2.csv		'measurement_date' is not in list
pitt_person_datasprint_2.csv			'birth_datetime' is not in list
pitt_procedure_occurrence_datasprint_2.csv	'procedure_date' is not in list
pitt_visit_occurrence_datasprint_2.csv		'visit_start_date' is not in list

Comparing the tables to the csv looks ok:
Table def			                       csv column header
CONDITION_START_DATE		CONDITION_START_DATE,
DRUG_EXPOSURE_START_DATE	DRUG_EXPOSURE_START_DATE,
MEASUREMENT_DATE		MEASUREMENT_DATE,

The Person file was different so I swapped "DATETIME_OF_BIRTH", to BIRTH_DATETIME and it still errors.

**Comment by mark-velez** [comment]
Ah I think the fix for #15 in reporter.py [line 166](https://github.com/cumc-dbmi/pmi_sprint_reporter/blob/c04e829efa75a19d443ff0390d7d8c40f642aa15/reporter.py#L166); made headers case sensitive (lowercase expected). I should have a fix for that soon.

Nonetheless, I think we'll continue to run into issues running this on oracle without coercing types on the dataframe fields before doing [df.to_sql](https://github.com/cumc-dbmi/pmi_sprint_reporter/blob/c04e829efa75a19d443ff0390d7d8c40f642aa15/reporter.py#L181). I've been meaning to do it, but haven't had time. And @johntmilnes you're the only one I know running this on Oracle. If you are interested in contributing, please let me know. ;)

Were you able to run this on sqlite?

**Comment by johntmilnes** [comment]
Hi Mark- No, sqllite is not useful to us as we are developing our QA processes around Oracle. Also, I expect other sites will want Oracle as well.  

As a test until you get  #15 fixed,  I swapped the headers on the input files to lowercase and 4 tables now load.
pitt_drug_exposure_datasprint_2.csv and pitt_measurement_datasprint_2.csv  still error with the convert to clob message.

I am not a developer and I assume that I am contributing by working through these issue with you ;)
